# Generated by Django 4.1.7 on 2023-04-10 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=15)),
                ('people', models.CharField(max_length=15)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('date', models.CharField(default='Yes', max_length=23)),
                ('checked', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirportTaxiService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(max_length=40)),
                ('car_type', models.CharField(default='sedan', max_length=10)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Regret', 'Regret'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('checked', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(max_length=20)),
                ('occupancy', models.CharField(max_length=15)),
                ('move_in_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('address', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('checked', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
