# Generated by Django 4.1.7 on 2023-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airporttaxiservice',
            old_name='user',
            new_name='client',
        ),
    ]
