# Generated by Django 4.1.7 on 2023-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_airporttaxiservice_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airporttaxiservice',
            name='order_id',
            field=models.CharField(default='Not Set', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
