# Generated by Django 4.1.7 on 2023-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_airporttaxiservice_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airporttaxiservice',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
