# Generated by Django 4.1.7 on 2023-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='checked',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
